spring:
  application:
    name: choice-eat-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

kakao:
  local:
    base-url: ${KAKAO_LOCAL_BASE_URL:https://dapi.kakao.com}
  rest-api-key: ${KAKAO_REST_API_KEY:}

ad:
  slots:
    repick: "ca-pub-xxxxxxxxxxxxxxxx/slot3" # 다시 뽑기 광고만 관리
